import "@/assets/css/globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import BaseHeader from "@/components/BaseHeader";
import BaseFooter from "@/components/BaseFooter";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { AuthProvider } from "@/components/ProviderAuth/ProviderAuth";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin-ext"],
  variable: "--font-poppins",
});
const logo = localFont({
  src: "../assets/fonts/logo.ttf",
  variable: "--font-logo",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({
    cookies,
  });
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessKey = session?.access_token ?? null;

  return (
    <html lang="en">
      <body
        className={`${logo.variable} ${poppins.variable} bg-white text-black`}
      >
        <AuthProvider accessToken={accessKey}>
          <BaseHeader />
          <main>{children}</main>
          <BaseFooter />
        </AuthProvider>
      </body>
    </html>
  );
}
