import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import BaseHeader from "@/components/BaseHeader";
const poppins = Poppins({
  weight: "500",
  subsets: ["latin-ext"],
  variable: "--font-poppins",
});
const logo = localFont({
  src: "../assets/fonts/logo.ttf",
  variable: "--font-logo",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${logo.variable} ${poppins.variable} bg-white text-black`}
      >
        <BaseHeader />
        {children}
      </body>
    </html>
  );
}
